@LivrosApi_HostAddress = http://localhost:5006

POST {{LivrosApi_HostAddress}}/admin/cadastro
Content-type: application/json
{
  "Username": "Henrique",
  "DataNascimento": "2003-10-30",
  "Cpf": "99877755521",
  "Password": "Admin1234!",
  "RePassword": "Admin1234!"
}
###
